#!/bin/bash

# Check the first argument
if [ "$1" == "" ]; then
    echo "Domain name is empty"
    exit
fi

# Check the seconds argument
if [ "$2" == "" ]; then
    echo "Intern address is empty"
    exit
fi

# Check the third argument
if [ "$3" == "" ]; then
    echo "To address is empty"
    exit
fi

# Set some values
EXIMPATH="/etc/exim4/virtual"
DOMAIN="$1"
CONFIGFILE="/$EXIMPATH/$DOMAIN"
INTERNMAIL="$2"
TOMAIL="$3"

# Check if the Exim config not exists
if [ ! -f "$CONFIGFILE" ]; then
    echo "Create Exim config file for domain $DOMAIN"
    touch "$CONFIGFILE"
else
    echo "Exim config file exists for domain $DOMAIN"
fi

# Add email address
echo "Add address to Exim config file"
echo "$INTERNMAIL $TOMAIL" >> "$CONFIGFILE"
