#!/bin/bash

# Check the first argument
if [ "$1" == "" ]; then
    echo "Website name is empty"
    exit
fi

# Set some values
SCRIPTPATH=`pwd -P`
WEBSITENAME="$1"

# Get the extension
if [ "$2" == "" ]; then
    EXTENSION="com"
else
    EXTENSION="$2"
fi

# Get the website type
if [ "$3" == "" ]; then
    WEBSITETYPE="default"
else
    WEBSITETYPE="$3"
fi

# Get the HTTP state
if [ "$4" == "https" ]; then
    HTTPS="https"
else
    HTTPS=""
fi

# Check if the website already exists
if [ -d "/home/$WEBSITENAME/" ]; then
    echo "Website already exists, stop bash script"
    exit
fi

# Add the user
echo "Creating user without shell access"
useradd -m -s /usr/sbin/nologin "$WEBSITENAME"

# Create www dir
echo "Creating www dir"
mkdir "/home/$WEBSITENAME/www"
chown "$WEBSITENAME":"$WEBSITENAME" "/home/$WEBSITENAME/www"

# Create database
./adddatabase "$WEBSITENAME"

# Create PHP-FPM pool
echo "Creating PHP-FPM pool"
PHPFULLVERSION=`php --version | head -n 1 | cut -d " " -f 2 | cut -c 1,2,3`
PHPCONFIGPATH="/etc/php/$PHPFULLVERSION/fpm/pool.d/$WEBSITENAME.conf"
sed "s/WEBSITE/$WEBSITENAME/g" "$SCRIPTPATH/configs/pool.conf" > "$PHPCONFIGPATH"

# Set PHP version
PHPNUMBERVERSION=`php --version | head -n 1 | cut -d " " -f 2 | cut -c 1,3`
sed -i -e "s/PHPVERSION/$PHPNUMBERVERSION/g" "$PHPCONFIGPATH"

# Create website config
./addwebsiteconfig "$WEBSITENAME" "$EXTENSION" "$WEBSITETYPE" "$HTTPS"

# Enable website
./enablewebsite "$WEBSITENAME"
