#!/bin/bash

# Check the first argument
if [ "$1" == "" ]; then
    echo "Website name is empty"
    exit
fi

# Set some values
SCRIPTPATH=`pwd -P`
SCRIPTCONFIGPATH="$SCRIPTPATH/configs/nginx"
NGINXCONFIGPATH="/etc/nginx/sites-available"
WEBSITENAME="$1"

# Get the extension
if [ "$2" == "" ]; then
    EXTENSION="com"
else
    EXTENSION="$2"
fi

# Get the website type
if [ "$3" == "" ]; then
    WEBSITETYPE="default"
else
    WEBSITETYPE="$3"
fi

# Get the HTTP state
if [ "$4" == "https" ]; then
    HTTPS="true"
else
    HTTPS="false"
fi

# Check HTTPS setting
if [ "$HTTPS" == "true" ]; then
    echo "HTTPS not supported, fall back to HTTP"
    HTTPS="false"
fi

# Get the config file
if [ "$HTTPS" == "true" ]; then
    CONFIGFILE=$WEBSITETYPE"_https.conf"
    CONFIGDEFAULTFILE="default_https.conf"
else
    CONFIGFILE=$WEBSITETYPE"_http.conf"
    CONFIGDEFAULTFILE="default_http.conf"
fi

# Check if Nginx config dir not exists; If not fall back to conf dir
if [ ! -d "$NGINXCONFIGPATH" ]; then
    NGINXCONFIGPATH="/etc/nginx/conf.d"
fi

# Check if the config file exists
if [ ! -f "$SCRIPTCONFIGPATH/$CONFIGFILE" ]; then
    echo "Website type not exists, fall back to default"
    CONFIGFILE="$CONFIGDEFAULTFILE"
fi

echo "$SCRIPTCONFIGPATH/$CONFIGFILE"

# Create Nginx config
echo "Creating Nginx config file"
sed "s/WEBSITE/$WEBSITENAME/g" "$SCRIPTCONFIGPATH/$CONFIGFILE" > "$NGINXCONFIGPATH/$WEBSITENAME"

# Set the extension
echo "Set the extension (.$EXTENSION)"
sed -i -e "s/EXTENSION/$EXTENSION/g" "$NGINXCONFIGPATH/$WEBSITENAME"
